# Application specific configurations
application:
  name: Book Store App

# Server configurations
server:
  port: :8080
  basepath: /book


# Database Configuration - postgres
database:
  driver: postgres
  dbname: bookapp
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  sslmode: disable
  timezone: UTC
  schema: bookapp
